server:
  port: 7005
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    loadbalancer:
      ribbon:
        enabled: false
